app = "stock-analysis-service"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpu_cores = 4
  memory_mb = 2048

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  processes = ["app"]  # Define which process this service runs

[services]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]  # Specify which process this service runs

[[services.ports]]
  handlers = ["http"]
  port = "80"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"

# Add health check
[[services.http_checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
  method = "get"
  path = "/health"
  protocol = "http"

# Configure logging
[logging]
  level = "info"

# Resource allocation limits
[processes]
  app = "python -m src.main"  # Define the app process

[metrics]
  port = 9091
  path = "/metrics" 