app = "stock-analysis-service"

# Add primary region configuration
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpu_cores = 4
  memory_mb = 2048

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"
  PYTHONUNBUFFERED = "1"

# Remove processes section since it's causing confusion with app type
# [processes]
#   worker = "python -m src.main"

# Add logging
[logging]
  level = "debug"

# Remove all HTTP service and health check configurations since this is a background service 