# fly.toml app configuration file
app = "stock-analysis-service"
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python -m src.main'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

# Add timeout settings
[deploy]
  strategy = "immediate"
  release_command = ""