app = "stock-analysis-service"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpu_cores = 4
  memory_mb = 2048

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"
  PYTHONUNBUFFERED = "1"

[processes]
  worker = "python -m src.main"

# Add health check process
[checks]
  [checks.worker]
    grace_period = "30s"
    interval = "15s"
    method = "tcp"
    port = 8080
    timeout = "2s"
    type = "tcp"

# Add logging
[logging]
  level = "debug"

# Remove all HTTP service and health check configurations since this is a background service 