# fly.toml app configuration file
app = "stock-analysis-service"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python -m src.main"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4

# Define service with process
[services]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]  # Specify which process this service runs

  [[services.ports]]
    port = "8080"

# Add logging
[logging]
  level = "debug"

# Remove all HTTP service and health check configurations since this is a background service 