# fly.toml app configuration file
app = "stock-analysis-service"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"
  PYTHONUNBUFFERED = "1"

# Define the process
[processes]
  worker = "python -m src.main"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4
  min_machines_running = 1

[logging]
  level = "debug" 