# fly.toml app configuration file
app = "stock-analysis-service"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"
  PYTHONUNBUFFERED = "1"

# Define as a background worker
[experimental]
  cmd = ["python", "-m", "src.main"]
  entrypoint = ["python", "-m", "src.main"]
  auto_rollback = true

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4
  min_machines_running = 1
  max_machines_running = 1

[logging]
  level = "debug" 