# fly.toml app configuration file
app = "stock-analysis-service"
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'
  TELEGRAM_BOT_TOKEN = '7530096691:AAEbEnXA2PJyihv0S3HD_5q1_pq6QRSj7-g'
  TELEGRAM_CHANNEL_ID = '-4678926083'
  ANALYSIS_INTERVAL = '3600'
  PORTFOLIO_THRESHOLD_SCORE = '75'

[processes]
  app = 'python -m src.main'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

# Add timeout settings
[deploy]
  strategy = "immediate"
  release_command = ""