app = "stock-analysis-service"

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"

# Specify machine size
[build]
  builder = "paketobuildpacks/builder:base"

# Configure VM resources
[[vm]]
  cpu_kind = "shared"
  cpu_cores = 4
  memory_mb = 2048
  min_instances = 1
  max_instances = 1

[services]
  internal_port = 8080
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = "80"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "30s"

# Add health check
[[services.http_checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "30s"
  method = "get"
  path = "/health"
  protocol = "http"

# Configure logging
[logging]
  level = "info"

# Resource allocation limits
[processes]
  web = "python -m src.main"

[metrics]
  port = 9091
  path = "/metrics" 