app = "stock-analysis-service"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpu_cores = 4
  memory_mb = 2048

[env]
  ANALYSIS_INTERVAL = "3600"  # 1 hour in seconds
  PORTFOLIO_THRESHOLD_SCORE = "75"

[processes]
  app = "python -m src.main"  # Define the app process

# Remove all HTTP service and health check configurations since this is a background service 